update sql scripts with new ascn table
ao508/cbioportal pull request #5
Opened 2019-08-26 13:44 UTC by averyniceday

ASCN sql changes. Haven't tested it yet - going to go through your code now! 
# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to master.
- [ ] If this is a bug fix, create a unit and/or e2e test, or explain why that cannnot be done.

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

2019-08-26 17:08 UTC, ao508 requested changes

2019-08-26 17:08 UTC, ao508 commented on core/src/main/java/org/mskcc/cbio/portal/dao/DaoAlleleSpecificCopyNumber.java
> +            pstmt = con.prepareStatement("SELECT MAX(`ASCB_ID`) FROM `allele_specific_copy_number`");
>ASCB_ID

typo?

2019-08-26 17:08 UTC, ao508 commented on core/src/main/java/org/mskcc/cbio/portal/dao/DaoAlleleSpecificCopyNumber.java
> +    // ***================ EVERYTHING UNDER HERE IS SUBJECT TO CHANGE ====================***
why are DaoMutation methods in here?

2019-08-26 17:08 UTC, ao508 commented on core/src/main/java/org/mskcc/cbio/portal/model/AlleleSpecificCopyNumber.java
> + * Copyright (c) 2019 Memorial Sloan-Kettering Cancer Center.
Mutation objects should remain in their own class

2019-08-26 17:08 UTC, ao508 commented on db-scripts/src/main/resources/cgds.sql
>    `DB_SCHEMA_VERSION` varchar(24),
need to update the version number at bottom of this script bc we're making a db change

2019-08-26 17:08 UTC, ao508 commented on db-scripts/src/main/resources/migration.sql
> +UPDATE `info` SET `DB_SCHEMA_VERSION`="3.1.0";
cgds.sql needs the updated version number as does the master pom.xml

2019-08-26 17:10 UTC, ao508 commented on db-scripts/src/main/resources/migration.sql
> +-- ========================== new ascn tables =============================================
>tables
--> `table`

2019-08-26 17:14 UTC, averyniceday commented
oops I've totally been pushing dev work into the same branch!! I meant to only open a PR with the sql changes! 😅

2019-08-27 14:49 UTC, ao508 requested changes
a few more changes to make and then this is ready to test IMO!

2019-08-27 14:49 UTC, ao508 commented on core/src/main/java/org/mskcc/cbio/portal/model/AlleleSpecificCopyNumber.java
> +public final class AlleleSpecificCopyNumber {
add `implements Serializable``` here

2019-08-27 14:49 UTC, ao508 commented on core/src/main/java/org/mskcc/cbio/portal/model/AlleleSpecificCopyNumber.java
> +public final class AlleleSpecificCopyNumber {
also, remove the `final` here as well

2019-08-27 14:49 UTC, ao508 commented on core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java
> +        for (AlleleSpecificCopyNumber ascn : ascnRecords) {
looks like some whitespace clean up here :)

2019-08-27 16:54 UTC, sheridancbio approved these changes
overall looks good

2019-08-27 16:54 UTC, sheridancbio commented on core/src/main/java/org/mskcc/cbio/portal/dao/DaoAlleleSpecificCopyNumber.java
> + * Copyright (c) 2015 Memorial Sloan-Kettering Cancer Center.
year needs update

2019-08-27 16:54 UTC, sheridancbio commented on core/src/main/java/org/mskcc/cbio/portal/model/AlleleSpecificCopyNumber.java
> + * Encapsulates Details regarding a Single Mutation.
maybe update class description comment

2019-08-27 16:54 UTC, sheridancbio commented on core/src/main/java/org/mskcc/cbio/portal/model/AlleleSpecificCopyNumber.java
> +    private long ascnId;
The other numeric type members do not use primitive classes .. they use Integer and Float ... should we use Long to be consistent?

2019-08-27 16:54 UTC, sheridancbio commented on core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java
> +
code updates here, so copyright can become "Copyright (c) 2015 - 2019"

2019-08-27 16:54 UTC, sheridancbio commented on core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java
> +            } catch (DaoException ex) {
I'm not sure what the reason is for catching the exception here and then rethrowing it

2019-08-27 16:54 UTC, sheridancbio commented on db-scripts/src/main/resources/cgds.sql
> +  `ASCN_ID` int(11),
I think we decided on BigInt for this

2019-08-27 16:54 UTC, sheridancbio commented on db-scripts/src/main/resources/cgds.sql
> +    `ASCN_ID` int(255) NOT NULL auto_increment,
BigInt?

2019-08-27 16:54 UTC, sheridancbio commented on db-scripts/src/main/resources/cgds.sql
> +INSERT INTO info VALUES ('3.1.0', NULL);
we talked about major v. minor schema version change

2019-08-27 17:22 UTC, merged